export const primaryDB = [
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
    { id: 10 },
    { id: 11 },
    { id: 12 },
    { id: 13 },
    { id: 14 },
    { id: 15 },
    { id: 16 },
  ];
  export const detailsDB = [
    { id: 1, label: "carlos" },
    { id: 2, label: "brian" },
    { id: 3, label: "Jp" },
    { id: 4, label: "Berto" },
    { id: 5, label: "Subway" },
    { id: 6, label: "Mcdonalds" },
    { id: 7, label: "Burger King" },
    { id: 8, label: "Wendys" },
    { id: 9, label: "Toyota" },
    { id: 10, label: "Honda" },
    { id: 11, label: "Jeep" },
    { id: 12, label: "Volkswagen" },
    { id: 13, label: "Ford" },
    { id: 14, label: "Chevy" },
    { id: 15, label: "Suburu" },
    { id: 16, label: "Kia" },
  ];
  