export const primaryDB = [
  { id: 1, label: "El Gord #4" },
  { id: 2, label: "El trompudo" },
  { id: 3, label: "Aguacates Hamburgers" },
  { id: 4, label: "Los Gallos" },
  { id: 5, label: "Subway" },
  { id: 6, label: "Mcdonalds" },
  { id: 5, label: "Subway" },
  { id: 6, label: "Mcdonalds" },
  { id: 7, label: "Burger King" },
  { id: 8, label: "Wendys" },
  { id: 9, label: "Carls Jr" },
  { id: 10, label: "Panda Express" },
  { id: 11, label: "Chilis" },
  { id: 12, label: "Quiznos" },
  { id: 13, label: "Togos" },
  { id: 14, label: "Pizza Hut" },
  { id: 15, label: "Dominos" },
  { id: 16, label: "Jack in the box" },
  { id: 17, label: "Taco Bell" },
  { id: 18, label: "In-N-Out" },
  { id: 19, label: "Wingstop" },
  
];
export const detailsDB = [
  { id: 1, name: "El Gord #4" ,worth: "60b", locations: 100 },
  { id: 2, name: "El trompudo" ,worth: "80b", locations: 4 },
  { id: 3, name: "Aguacates Hamburgers"  ,worth: "100b", locations: 1 },
  { id: 4, name: "Los Gallos" ,worth: "120b", locations: 3 },
  { id: 5, name: "Subway", worth: "20b", locations: 1050 },
  { id: 6, name: "Mcdonalds", worth: "50b", locations: 5000 },
  { id: 7, name: "Burger King", worth: "20b", locations: 1500 },
  { id: 8, name: "Wendys", worth: "10b", locations: 2000 },
  { id: 9, name: "Carls Jr", worth: "20b", locations: 2000 },
  { id: 10, name: "Panda Express", worth: "30b", locations: 3000 },
  { id: 11, name: "Chilis", worth: "40b", locations: 1000 },
  { id: 12, name: "Quiznos", worth: "50b", locations: 1000 },
  { id: 13, name: "Togos", worth: "60b", locations: 2000 },
  { id: 14, name: "Pizza Hut", worth: "10b", locations: 2700 },
  { id: 15, name: "Dominos", worth: "20b", locations: 2000 },
  { id: 16, name: "Jack in the box", worth: "20b", locations: 3000 },
  { id: 17, name: "Taco Bell", worth: "5b", locations: 10000 },
  { id: 18, name: "In-N-Out", worth: "10b", locations: 1000 },
  { id: 19, name: "Wingstop", worth: "8b", locations: 1000 },
];
